language: c

os: linux
sudo: false
dist: trusty
compiler: gcc

addons:
    apt:
        packages:
        - ninja-build
        - realpath
        - lua5.2
        - pasmo
        - libz80ex-dev
        - lemon

script:
    - make

