language: c

os: linux
sudo: true
dist: trusty
compiler: gcc

addons:
    apt:
        packages:
        - ninja-build
        - realpath
        - lua5.2
        - pasmo
        - libz80ex-dev

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.3.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.3.1-linux-x86_64.deb

script:
    - bin/bazel //src/...

