name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: sudo apt install ninja-build realpath lua5.2 pasmo libz80ex-dev lemon
    - name: make
      run: make

