name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: sudo apt install ninja-build lua5.2 pasmo libz80ex-dev:i386 flex libbsd-dev:i386 libreadline-dev:i386 bison
    - name: make
      run: make

